### ISSUE TITLE
Add modifiers to imagine instruction

### ISSUE THREAD

**Issue by VisLab** [BigEEGConsortium/HED-schema#6]
Event/Category/Experimental stimulus/Instruction/Imagine/Movement
Event/Category/Experimental stimulus/Instruction/Imagine/Emotion

**Comment by bigdelys** [comment]
1)
Use 
Event/Category/Experimental stimulus/Instruction, (Attribute/Instruction, Attribute/Imagined,  Action/Move)

for

Event/Category/Experimental stimulus/Instruction/Imagine/Movement

2) Use 

Event/Category/Experimental stimulus/Instruction, (Attribute/Instruction, Attribute/Imagined,  Participant/State/Emotion/XXX)

Instead of 

Event/Category/Experimental stimulus/Instruction/Imagine/Emotion/XXX
